# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A COVID-19 Journal'
description:         'One man’s experiences in the US during the COVID-19 Pandemic.'
url:                 https://thiscovidlife.github.io/blog/
baseurl:             ''
paginate:            5
plugins:             [jekyll-paginate]
paginate_path:       'page:num'

# About/contact
author:
  name:              John
  url:               https://twitter.com/johnregan3
  email:             nobody@gmail.com

# Custom vars
version:             1.0.0
